apiVersion: v1
kind: Service
metadata:
  name: go-docker-k8s-service
  namespace: dev
spec: 
  selector:
    app: go-docker-k8s-pod
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80 #external
      targetPort: 8080 #internal
  