name: CI/CD to Docker Hub + Minikube

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/go-docker-k8s

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build Go binary
        run: |
          $env:CGO_ENABLED="0"
          $env:GOOS="linux"
          $env:GOARCH="amd64"
          go build -o server .

      - name: Check Docker username (Windows-safe)
        run: |
          if ($env:DOCKER_USERNAME -eq $null -or $env:DOCKER_USERNAME -eq "") {
            Write-Host "DOCKER_USERNAME is missing!"
            exit 1
          } else {
            Write-Host "DOCKER_USERNAME is set."
          }


      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:0.0.1 .
          docker push $IMAGE_NAME:0.0.1

      - name: Deploy to Minikube
        run: |
          kubectl apply -f k8s/Deployment.yaml
          kubectl apply -f k8s/Service.yaml
          kubectl rollout status deployment/go-docker-k8s -n dev
